### ISSUE TITLE
size_t count inside ecs_array_t never updated

### ISSUE THREAD

**Issue by emre-nevayeshirazi** [empyreanx/pico_headers#7]
```
typedef struct
{
    size_t capacity;
    size_t count; 
    size_t size;
    void* data;
} ecs_array_t;
```
The `size_t count` variable inside ecs_array_t never gets updated.

**Comment by empyreanx** [comment]
The `size` member of `ecs_array_t` is only given a value at initialization, it is the size of individual elements. That naming is confusing so I'll revise it.  The `count` member is the number of elements present in the array. I hope this helps!

**Comment by emre-nevayeshirazi** [comment]
Yes, I meant the count (`size_t count`) member which is never updated.

**Comment by empyreanx** [comment]
I see your point. Somehow I managed to neglect that. I think a fix should be relatively straightforward, with the possible exception of resizing the sparse arrays.  Tomorrow I'll put some energy into putting together a potential fix. Thanks for bringing this up. I'm surprised, however, that it didn't failed in testing. I'll put it through valgrind again and what comes up.

**Comment by empyreanx** [comment]
Upon further review it seems that `array->count` is not used because it is unnecessary. The `ecs_array_t` struct is only used by the component arrays and the component arrays rely only on the capacity of the array. I think is some refactoring might be in order to make this more explicit. For example renaming `ecs_array_t` to `ecs_comp_array_t` and perhaps renaming `ecs_array_resize` to something more descriptive.

**Comment by emre-nevayeshirazi** [comment]
Thanks. As far as I remember the count member is never used in the code. That could be why tests never detected the issue.
Also thanks for the library, after testing many archetype based ECS frameworks, I found the pico.
It is very fast, easy to work with and easy to modify.

**Comment by empyreanx** [comment]
Great! I'm glad you find it useful.
